   <link rel="stylesheet" href="includes\chatbot.css">

<div class="body62">

<div class="container62">
    <div class="content62">
        <h1>🌿 Our Chat Bot 🌿</h1>
        <p>If you have any questions or queries about plants, gardening and anything else, you should use our CHAT BOT. </p>
        <p>You can take advance tips or patterns to plant your seeds. </p>

        <p>Or if you want to shop</p> <a href="#shop-here"><button>Click Here</button></a>
    </div>

    <div class="chatbot" id="chatbot-container">
        <h2>🌿 Gardening Chatbot 🌿</h2>
        <div id="chat-content" class="chat-messages">
            <div class="message62">Welcome! Ask me about gardening.</div>
        </div>
        <div class="chatbox">
            <input type="text" id="user-input" class="message-input" placeholder="Type your question..." />
            <button id="send-btn" class="send-button">Send</button>
        
</div>

<script>
    const sendBtn = document.getElementById("send-btn");
    const userInput = document.getElementById("user-input");
    const chatContent = document.getElementById("chat-content");
    const closeBtn = document.getElementById("close-btn");

    const knowledgeBase = {
        "plant": "Grow",
    "seed": "Sprout",
    "water": "Drink",
    "soil": "Dirt",
    "sun": "Shine",
    "leaf": "Green",
    "root": "Deep",
    "tree": "Tall",
    "flower": "Pretty",
    "grass": "Lawn",
    "worm": "Wiggle",
    "rock": "Hard",
    "mud": "Sticky",
    "rain": "Wet",
    "dirt": "Messy",
    "vine": "Climb",
    "fruit": "Sweet",
    "weed": "Annoying",
    "bug": "Tiny",
    "pot": "Container","photosynthesis": "Energy",
    "plant absorb": "Water",
    "plant release": "Oxygen",
    "roots function": "Anchor",
    "compost made of": "Organic",
    "soil pH": "Balance",
    "flowers attract": "Pollinators",
    "vermicomposting": "Worms",
    "greenhouse use": "Protection",
    "leaves contain": "Chlorophyll",
    "hydroponics": "Water",
    "mulching for": "Moisture",
    "seed need": "Germination",
    "nitrogen helps": "Growth",
    "bees collect": "Nectar",
    "phosphorus helps": "Roots",
    "sunlight needed": "Photosynthesis",
    "best soil": "Loamy",
    "fungus control": "Neem",
    "fertilizer type": "Organic",
    "watering time": "Morning",
    "companion planting": "Basil",
    "best mulch": "Straw",
    "pests control": "Insecticidal Soap",
    "pruning time": "Spring",
    "crop rotation": "Health",
    "germination need": "Moisture",
    "heirloom seeds": "Heritage",
    "mulch types": "Bark",
    "pH level good": "Neutral",
    "soil nutrients": "Nitrogen",
    "raised beds": "Drainage",
    "organic pesticide": "Neem Oil",
    "best fertilizer": "Compost",
    "shade plants": "Hostas",
    "pollinators": "Bees",
    "drought plants": "Cactus",
    "pest trap": "Sticky",
    "herb growing": "Basil",
    "soil amendment": "Manure",
    "vegetable spacing": "Depends",
    "best flower food": "Phosphorus",
    "root rot": "Overwatering",
    "watering method": "Drip",
    "leaf color change": "Nutrients",
    "garden pest": "Aphids",
    "fungal disease": "Powdery Mildew",
    "soil texture": "Sandy",
    "best garden tool": "Trowel",
    "fertilizer need": "Spring",
    "topsoil depth": "Six Inches",
    "fastest growing": "Radish",
    "planting season": "Spring",
    "perennial example": "Lavender",
    "annual example": "Marigold",
    "tree type": "Deciduous",
    "weed control": "Mulch",
    "best compost": "Kitchen Scraps",
    "grafting": "Union",
    "mulching benefits": "Weeds",
    "organic gardening": "Natural",
    "pruning tool": "Shears",
    "raised bed material": "Wood",
    "beneficial insects": "Ladybugs",
    "root type": "Taproot",
    "container plant": "Tomato",
    "best indoor plant": "Snake Plant",
    "soil drainage": "Sand",
    "fungal prevention": "Airflow",
    "garden pollinators": "Butterflies",
    "plant reproduction": "Seeds",
    "tree food": "Photosynthesis",
    "best soil mix": "Loam",
    "fertilizer contains": "Nitrogen",
    "leaf function": "Photosynthesis",
    "stem function": "Support",
    "flower part": "Petal",
    "companion for tomatoes": "Basil",
    "best vegetable soil": "Loamy",
    "prune roses": "Spring",
    "biodiversity importance": "Ecosystem",
    "fastest sprouting seed": "Lettuce",
    "best plant light": "Sunlight",
    "leaf spots": "Fungus",
    "root disease": "Rot",
    "pesticide alternative": "Soap Spray",
    "best watering method": "Drip",
    "air plant needs": "Humidity",
    "succulent soil": "Sandy",
    "best potted soil": "Drainage",
    "herb drying method": "Hanging",
    "natural fertilizer": "Compost",
    "best seed starter": "Peat",
    "vegetable spacing importance": "Growth",
    "tomato pest": "Hornworm",
    "best garden location": "Sunny",
    "worm composting": "Vermiculture",
    "compost smell": "Earthy",
    "water plant frequency": "Depends",
    "nutrient deficiency": "Yellow Leaves",
    "best flowering season": "Spring",
    "best fruit tree": "Apple",
    "best plant for bees": "Lavender",
    "best edible flower": "Nasturtium",
    "best pollinator flower": "Sunflower",
    "best medicinal plant": "Aloe Vera",
    "best drought plant": "Cactus",
    "best climbing plant": "Ivy",
    "low maintenance plant": "Succulent",
    "easy vegetable": "Radish",
    "hardest vegetable": "Cauliflower",
    "compost time": "Three Months",
    "best plant for beginners": "Basil",
    "best shade tree": "Maple",
    "best sun plant": "Rose",
    "best garden mulch": "Straw",
    "best garden layout": "Raised Beds",
    "best plant propagation": "Cuttings",
    "root division plant": "Hosta",
    "best organic mulch": "Leaves",
    "best plant for small space": "Lettuce",
    "best fast growing tree": "Willow",
    "best perennial herb": "Thyme",
    "best soil moisture": "Damp",
    "best soil amendment": "Compost",
    "companion for beans": "Corn",
    "companion for peppers": "Carrots",
    "best garden pest control": "Neem",
    "best pruning season": "Winter",
    "best plant for erosion control": "Grass",
    "best fruit for small space": "Strawberry",
    "best composting method": "Aerobic",
    "best way to attract butterflies": "Milkweed",
    "best way to prevent disease": "Spacing",
    "best garden tool for weeding": "Hoe",
    "best vegetable for beginners": "Lettuce",
    "best flowering plant": "Rose",
    "best vegetable to grow in pots": "Tomatoes",
    "best climbing vegetable": "Beans",
    "best fertilizer for flowers": "Phosphorus",
    "best vegetable for hot climate": "Peppers",
    "best vegetable for cool climate": "Spinach",
    "best vegetable for winter": "Kale",
    "best vegetable for summer": "Cucumber",
    "best container soil": "Potting Mix",
    "best garden watering method": "Drip Irrigation",
    "best soil for herbs": "Well-Drained",
    "best organic fertilizer": "Manure",
    "best fast growing vegetable": "Radish",
    "best vegetable for raised beds": "Carrots",
    "best companion plant for cabbage": "Dill",
    "best companion plant for carrots": "Onions",
    "best way to remove weeds": "Hand-Pulling",
    "best companion for lettuce": "Radish",
    "best plant for humidity": "Fern",
    "best plant for air purification": "Spider Plant",
    "best fruit for pollinators": "Blueberry",
    "best vegetable for vertical garden": "Cucumber",
    "best ground cover plant": "Clover",
    "best herb for tea": "Mint",
    "best soil for orchids": "Bark Mix","what is your name": "I'm a Smart Chatbot. I can answer any question you have!",
    "how are you": "I'm doing great, thank you for asking! How can I assist you today?",
    "what is javascript": "JavaScript is a programming language used to create dynamic and interactive effects on web pages.",
    "who are you": "I am a chatbot designed to help you with any questions. Just ask away!",
    "who won the world series": "The 2024 World Series was won by the Los Angeles Dodgers.",
    "what is the capital of france": "The capital of France is Paris.",
    "how does a plant grow": "Plants grow by absorbing water and sunlight, and using nutrients in the soil to produce energy.",
    "tell me a joke": "Why don't skeletons fight each other? They don't have the guts!",
    "weather today": "I can't fetch real-time weather data, but you can check your local weather app for today's forecast.",
    "watering": "Most plants need to be watered once a week. However, check your plant's specific needs!",
    "sunlight": "Plants need sunlight to grow. Most indoor plants thrive in indirect sunlight.",
    "soil": "Ensure your plant is in well-draining soil to avoid root rot. Each plant has a specific soil preference.",
    "indoor plants": "Common indoor plants include snake plants, pothos, and succulents. Make sure to place them in suitable light.",
    "fertilizer": "Fertilizing your plants regularly can encourage healthy growth. Choose the right fertilizer for your plant type.",
    "pests": "Check your plants regularly for pests like aphids and spider mites. Neem oil is a great natural solution.",
    "growth": "Plants need proper care, water, and sunlight to grow. Patience is key!",
    "what is a plant": "A plant is a living organism that absorbs water and nutrients through its roots, uses sunlight for photosynthesis, and has stems, leaves, and flowers.",
    "how do plants grow": "Plants grow by absorbing sunlight, water, and nutrients from the soil. They use photosynthesis to convert sunlight into energy.",
    "what is photosynthesis": "Photosynthesis is the process by which plants convert sunlight into chemical energy to produce food. They absorb carbon dioxide and release oxygen.",
    "why do plants need sunlight": "Plants need sunlight for photosynthesis, which is how they make their food. Sunlight helps plants produce glucose, which is used for energy.",
    "how do you water plants": "Most plants need to be watered thoroughly, ensuring that the water reaches the roots. It's important not to overwater, as it can cause root rot.",
    "how often should you water indoor plants": "Indoor plants generally need watering once a week, but it depends on the plant type and environmental conditions like humidity and temperature.",
    "what is root rot": "Root rot is a condition where plant roots decay due to excess water, poor drainage, or a lack of oxygen. It can kill the plant if untreated.",
    "what is a succulent": "A succulent is a type of plant that stores water in its leaves, stems, or roots. They thrive in dry conditions and often have fleshy, thick leaves.",
    "how do you take care of succulents": "Succulents need bright, indirect sunlight, infrequent watering, and well-draining soil. Avoid overwatering, as they are prone to root rot.",
    "what is the best soil for plants": "The best soil for most plants is well-draining soil that holds some moisture but doesn't become waterlogged. A mix of compost and perlite is ideal.",
    "what is compost": "Compost is decomposed organic matter used to fertilize soil. It provides nutrients to plants and improves soil structure.",
    "how do you prune plants": "Pruning involves cutting back overgrown stems or leaves to encourage healthier growth. Use sharp tools and trim dead or diseased parts of the plant.",
    "why are my plant leaves turning yellow": "Yellow leaves can indicate several issues, such as overwatering, underwatering, nutrient deficiencies, or pests. It's important to check the plant's environment and care routine.",
    "how do you repot a plant": "To repot a plant, gently remove it from its current pot, shake off excess soil, and place it in a new pot that is slightly larger. Add fresh soil around the roots and water thoroughly.",
    "when should you repot a plant": "Plants should be repotted every 1-2 years or when their roots outgrow their pot. Signs that a plant needs repotting include roots growing out of the drainage holes or poor growth.",
    "what is a plant's lifecycle": "A plant's lifecycle consists of stages: seed, germination, growth, flowering, pollination, and seed production. Some plants are annuals, while others are perennials.",
    "what is pollination": "Pollination is the process where pollen is transferred from the male part of a flower to the female part, leading to fertilization and seed production.",
    "what is a perennial plant": "Perennials are plants that live for more than two years. They usually flower and produce seeds in their second or subsequent years of growth.",
    "what is an annual plant": "Annual plants complete their life cycle in one year. They grow, flower, produce seeds, and die in the same growing season.",
    "what is a biennial plant": "Biennials are plants that take two years to complete their life cycle. They grow in the first year and flower, seed, and die in the second year.",
    "how do you grow a tree": "To grow a tree, start by selecting a suitable location with good soil and sunlight. Plant a young tree in a hole twice as wide as its root ball and water regularly.",
    "how do you start seeds indoors": "To start seeds indoors, plant them in seed trays with seed-starting mix. Keep them warm and provide plenty of light, either from windows or grow lights.",
    "how do you transplant seedlings": "Transplant seedlings when they have developed strong roots and at least two sets of leaves. Gently remove them from their pots, and plant them in larger containers or the garden.",
    "what is mulch": "Mulch is a layer of material applied to the soil surface to retain moisture, suppress weeds, and regulate soil temperature. It can be organic (like bark or leaves) or inorganic (like gravel).",
    "what are common houseplants": "Common houseplants include snake plants, pothos, peace lilies, spider plants, succulents, and philodendrons. These plants thrive indoors and are easy to care for.",
    "what is the best light for indoor plants": "Indoor plants generally thrive with bright, indirect sunlight. Some plants, like succulents, need direct sunlight, while others, like ferns, prefer low light.",
    "how do you fix overwatering": "To fix overwatering, remove the plant from its pot and allow the roots to dry out. Trim any rotten roots and repot the plant in fresh, well-draining soil.",
    "how do you fix underwatering": "If a plant is underwatered, thoroughly water it, ensuring the water reaches the roots. If the plant looks wilted, prune any dead or dry leaves and continue to water regularly.",
    "what is a cactus": "A cactus is a type of succulent plant that is adapted to survive in dry, desert environments. They have thick, fleshy stems that store water and spines for protection.",
    "how do you care for a cactus": "Cacti need bright, direct sunlight, infrequent watering, and well-draining soil. Be careful not to overwater, as cacti are prone to root rot.",
    "what are the signs of a plant being stressed": "Signs of plant stress include wilting, yellowing leaves, brown leaf edges, stunted growth, and leaf drop. Stress can be caused by overwatering, underwatering, pests, or poor light.",
    "what is the best fertilizer for plants": "The best fertilizer depends on the type of plant. A balanced fertilizer with equal amounts of nitrogen, phosphorus, and potassium works for most plants. Organic fertilizers like compost are also good options.",
    "how do you deal with pests on plants": "To deal with pests, first identify the type of pest. You can remove pests manually, use insecticidal soap, neem oil, or introduce beneficial insects like ladybugs to control the pests.",
    "how do you prevent plant pests": "Prevent pests by maintaining good plant hygiene, removing dead leaves, and regularly inspecting plants for early signs of pests. Good air circulation also helps prevent infestations.",
    "what are aphids": "Aphids are small, soft-bodied insects that suck sap from plants. They can cause yellowing leaves, stunted growth, and the spread of diseases. Control aphids with insecticidal soap or natural predators like ladybugs.",
    "what is neem oil": "Neem oil is a natural insecticide made from the neem tree. It can be used to control a wide range of pests, including aphids, mealybugs, and spider mites. It is safe for most plants.",
    "how do you care for a bonsai tree": "Bonsai trees require careful pruning, wiring, and shaping. They also need regular watering, well-draining soil, and plenty of indirect sunlight. Fertilize them monthly during the growing season.",
    "how do you grow herbs indoors": "To grow herbs indoors, provide them with plenty of sunlight (at least 6 hours a day), well-draining soil, and regular watering. Popular herbs for indoor growing include basil, mint, and parsley.",
    "what is a fern": "A fern is a type of non-flowering plant with fronds (leaves) that grow from rhizomes (underground stems). They thrive in humid environments with indirect light.",
    "how do you care for a fern": "Ferns need high humidity, indirect light, and regular watering. Keep the soil consistently moist, but avoid waterlogging. You can also mist the leaves to maintain humidity.",
    "how do you grow orchids": "Orchids need bright, indirect light, high humidity, and well-draining, acidic soil. They should be watered once a week, allowing the soil to dry out between waterings.",
    "what is the best way to propagate plants": "Common methods of propagation include stem cuttings, leaf cuttings, and division. Some plants can also be propagated by seeds or by layering their stems into the soil.",
    "how do you grow strawberries": "To grow strawberries, plant them in well-drained soil in a sunny location. Keep the soil moist, and provide a mulch to protect the berries from pests and diseases.",
    "how do you grow tomatoes": "Tomatoes need plenty of sunlight, warm temperatures, and rich, well-drained soil. Water them regularly and provide support for the vines as they grow.",
    "what is the best time to plant flowers": "The best time to plant flowers depends on the climate and the type of flower. Most flowers are planted in the spring after the danger of frost has passed.",
    "what is the best time to plant trees": "The best time to plant trees is in the fall or early spring, when temperatures are mild, and the tree has time to establish its roots before the hot summer or cold winter.",
    "how do you grow vegetables": "To grow vegetables, select a sunny spot, prepare the soil by adding compost, and plant seeds or seedlings. Water regularly, and be sure to harvest at the appropriate time.",
    "how do you grow carrots": "Carrots grow best in deep, loose, well-drained soil. They need full sunlight and regular watering. Thin out the seedlings to give them enough space to grow.",
    "how do you grow potatoes": "Potatoes are grown from seed potatoes, which are planted in loose, well-draining soil. They need full sunlight and consistent moisture to grow.",
    "how do you grow lettuce": "Lettuce grows best in cool weather with plenty of sunlight. It prefers well-draining soil and needs to be watered regularly to keep the leaves crisp.",
    "what is a raised garden bed": "A raised garden bed is a garden plot that is raised above the surrounding soil. It provides better drainage, soil quality, and easier access for gardening.",
    "what is hydroponics": "Hydroponics is a method of growing plants without soil, using a nutrient-rich water solution instead. It is often used for growing vegetables and herbs indoors or in greenhouses.",
    "what is aquaponics": "Aquaponics is a combination of hydroponics and aquaculture (fish farming). It involves growing plants in water while raising fish, whose waste provides nutrients for the plants.",
    "what are carnivorous plants": "Carnivorous plants are plants that capture and digest insects for nutrients. Examples include Venus flytraps, pitcher plants, and sundews.",
    "how do you care for a carnivorous plant": "Carnivorous plants need a humid environment, lots of sunlight, and nutrient-poor soil. Avoid fertilizing them with regular plant food, as they obtain nutrients from insects.",
    "what is a terrarium": "A terrarium is a small, enclosed container that houses plants, creating a self-sustaining ecosystem. It provides high humidity and a controlled environment for tropical plants.",
    "what is a flower bulb": "A flower bulb is a plant structure that stores nutrients and energy for the plant. Common bulbs include tulips, daffodils, and lilies. Bulbs are planted underground and bloom in the spring.",
    "how do you plant flower bulbs": "Plant flower bulbs in the fall, about 3-4 inches deep, with the pointed end facing up. Ensure they are planted in well-drained soil and receive plenty of sunlight.",
    "how do you grow a lawn": "To grow a lawn, choose the right grass type for your region, prepare the soil by aerating and fertilizing it, and seed it evenly. Water regularly and mow the grass to the appropriate height.",
    "what is topsoil": "Topsoil is the uppermost layer of soil, which contains the highest concentration of organic matter and nutrients. It is crucial for plant growth.",
    "how do you improve soil quality": "To improve soil quality, add organic matter like compost, mulch, or manure. You can also aerate the soil and ensure it has proper drainage for healthy plant growth.",
    "how do you make your own compost": "To make compost, collect organic waste like vegetable scraps, leaves, grass clippings, and coffee grounds. Pile them in a compost bin, turning the mixture regularly to encourage decomposition.",
    "what is a raised bed garden": "A raised bed garden is a gardening method where soil is raised above ground level. It provides better drainage and easier access while reducing soil compaction.",
    "how do you harvest herbs": "To harvest herbs, cut the leaves or stems when the plant is actively growing. Use scissors or pruning shears to avoid damaging the plant.",
    "what are common garden pests": "Common garden pests include aphids, snails, slugs, spider mites, and caterpillars. They can be controlled using organic methods like neem oil or beneficial insects like ladybugs.",
    "how do you prevent weeds": "To prevent weeds, use mulch to cover the soil, regularly pull out weeds by hand, or use a weed barrier fabric. Consistent maintenance will keep them under control.",
    "what is the capital of France": "The capital of France is Paris.",
    "who invented the telephone": "The telephone was invented by Alexander Graham Bell in 1876.",
    "how far is the moon from Earth": "The average distance from the Earth to the moon is about 384,400 kilometers (238,855 miles).",
    "what is the largest animal on Earth": "The largest animal on Earth is the blue whale, which can grow up to 100 feet (30 meters) long.",
    "who is the president of the United States": "As of 2025, the president of the United States is Joe Biden.",
    "what is the longest river in the world": "The longest river in the world is the Nile River, which is about 6,650 kilometers (4,130 miles) long.",
    "how many continents are there": "There are seven continents on Earth: Africa, Antarctica, Asia, Europe, North America, Australia, and South America.",
    "what is the smallest country in the world": "The smallest country in the world is Vatican City, with an area of just 44 hectares (110 acres).",
    "who was the first man to walk on the moon": "Neil Armstrong was the first man to walk on the moon on July 20, 1969, during the Apollo 11 mission.",
    "what is the speed of light": "The speed of light in a vacuum is approximately 299,792 kilometers per second (186,282 miles per second).",
    "what is the boiling point of water": "The boiling point of water is 100°C (212°F) at sea level under normal atmospheric pressure.",
    "who wrote 'Romeo and Juliet'": "'Romeo and Juliet' was written by William Shakespeare in 1597.",
    "what is the tallest mountain in the world": "The tallest mountain in the world is Mount Everest, which stands at 8,848 meters (29,029 feet) above sea level.",
    "what is the capital of Japan": "The capital of Japan is Tokyo.",
    "how many planets are there in the solar system": "There are eight planets in the solar system: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, and Neptune.",
    "what is the largest ocean in the world": "The largest ocean in the world is the Pacific Ocean.",
    "what is the hardest natural substance on Earth": "The hardest natural substance on Earth is diamond.",
    "who painted the Mona Lisa": "The Mona Lisa was painted by Leonardo da Vinci between 1503 and 1506.",
    "what is the deepest ocean in the world": "The deepest ocean in the world is the Pacific Ocean, with the Mariana Trench being the deepest point.",
    "how many bones are in the human body": "There are 206 bones in the adult human body.",
    "what is the human brain weight": "The average human brain weighs about 1.4 kilograms (3 pounds).",
    "who discovered gravity": "Gravity was discovered by Sir Isaac Newton in the 17th century.",
    "what is the largest desert in the world": "The largest desert in the world is the Antarctic Desert, covering an area of 14 million square kilometers (5.4 million square miles).",
    "what is the largest city in the world by population": "The largest city in the world by population is Tokyo, Japan.",
    "what is the smallest bone in the human body": "The smallest bone in the human body is the stapes, located in the middle ear.",
    "how many states are in the United States": "There are 50 states in the United States.",
    "what is the longest bridge in the world": "The Danyang–Kunshan Grand Bridge in China is the longest bridge in the world, measuring 164.8 kilometers (102.4 miles).",
    "who was the first woman to fly solo across the Atlantic": "Amelia Earhart was the first woman to fly solo across the Atlantic Ocean in 1932.",
    "how many teeth does an adult human have": "An adult human typically has 32 teeth, including wisdom teeth.",
    "what is the symbol for gold on the periodic table": "The symbol for gold on the periodic table is Au.",
    "who discovered penicillin": "Penicillin was discovered by Alexander Fleming in 1928.",
    "what is the currency of Japan": "The currency of Japan is the Japanese Yen (JPY).",
    "what is the longest-running TV show in the US": "The longest-running TV show in the US is 'The Simpsons,' which first aired in 1989.",
    "what is the tallest building in the world": "The tallest building in the world is the Burj Khalifa in Dubai, United Arab Emirates, standing at 828 meters (2,717 feet).",
    "what is the largest planet in the solar system": "The largest planet in the solar system is Jupiter.",
    "who wrote the Declaration of Independence": "The Declaration of Independence was primarily written by Thomas Jefferson in 1776.",
    "how long does it take for the Earth to orbit the Sun": "It takes the Earth approximately 365.25 days to orbit the Sun, which is one year.",
    "what is the capital of Canada": "The capital of Canada is Ottawa.",
    "what is the chemical formula for water": "The chemical formula for water is H2O.",
    "what is the smallest planet in the solar system": "The smallest planet in the solar system is Mercury.",
    "how many colors are there in a rainbow": "A rainbow traditionally has seven colors: red, orange, yellow, green, blue, indigo, and violet.",
    "what is the official language of Brazil": "The official language of Brazil is Portuguese.",
    "what is the hardest known metal": "The hardest known metal is tungsten.",
    "who was the first president of the United States": "The first president of the United States was George Washington, who served from 1789 to 1797.",
    "what is the longest movie ever made": "The longest movie ever made is 'Logistics,' which is 857 hours (35 days and 17 hours) long.",
    "how many ribs does a human have": "A human typically has 24 ribs, 12 on each side of the body.",
    "what is the smallest country in Africa": "The smallest country in Africa by land area is Seychelles.",
    "what is the national flower of Japan": "The national flower of Japan is the cherry blossom (sakura).",
    "who is known as the 'Father of Modern Physics'": "Albert Einstein is known as the 'Father of Modern Physics' due to his contributions to the theory of relativity.",
    "what is the tallest waterfall in the world": "The tallest waterfall in the world is Angel Falls in Venezuela, with a height of 979 meters (3,212 feet).",
    "who invented the light bulb": "Thomas Edison is credited with inventing the first commercially successful light bulb in 1879.",
    "what is the currency of the United Kingdom": "The currency of the United Kingdom is the British Pound Sterling (GBP).",
    "what is the capital of Italy": "The capital of Italy is Rome.",
    "what is the largest volcano in the world": "The largest volcano in the world is Mauna Loa in Hawaii, covering an area of 5,271 square kilometers (2,035 square miles).",
    "who wrote '1984'": "'1984' was written by George Orwell and published in 1949.",
    "how many years are in a century": "There are 100 years in a century.",
    "what is the deepest point on Earth": "The deepest point on Earth is the Challenger Deep in the Mariana Trench, located 10,994 meters (36,070 feet) below sea level.",
    "who discovered America": "Christopher Columbus is credited with discovering America in 1492, although indigenous peoples had been living on the continent for thousands of years.",
    "what is the largest island in the world": "The largest island in the world is Greenland.",
    "what is the distance from the Earth to the Sun": "The average distance from the Earth to the Sun is about 149.6 million kilometers (93 million miles).",
    "how many players are on a soccer team": "A soccer team consists of 11 players, including the goalkeeper.",
    "what is the national animal of India": "The national animal of India is the Bengal tiger.",
    "who invented the airplane": "The Wright brothers, Orville and Wilbur Wright, invented and successfully flew the first powered airplane in 1903.",
    "what is the capital of Germany": "The capital of Germany is Berlin.",
    "how many elements are in the periodic table": "There are currently 118 confirmed elements in the periodic table.",
    "what is the smallest country in Asia": "The smallest country in Asia by land area is the Maldives.",
    "what is the tallest tree in the world": "The tallest tree in the world is a coast redwood (Sequoia sempervirens) named Hyperion, which stands at 379.7 feet (115.7 meters).",
    "what is the fastest animal on land": "The fastest land animal is the cheetah, which can run at speeds of up to 70 miles per hour (113 kilometers per hour).",
    "how many seasons are there in a year": "There are four seasons in a year: spring, summer, fall, and winter.",
    "what is the largest species of shark": "The largest species of shark is the whale shark, which can grow up to 12 meters (40 feet) long.",
    "who was the first person to break the sound barrier": "Chuck Yeager was the first person to break the sound barrier in 1947.",
    "what is the capital of Spain": "The capital of Spain is Madrid.",
    "who is the author of 'Harry Potter'": "'Harry Potter' was written by J.K. Rowling, with the first book published in 1997.",
    "what is the national animal of Australia": "The national animal of Australia is the red kangaroo.",
    "what is the smallest mammal": "The smallest mammal in the world is the bumblebee bat, weighing less than a penny.",
    "how long is the Great Wall of China": "The Great Wall of China stretches over 21,196 kilometers (13,171 miles).",
    "who was the first woman to win a Nobel Prize": "Marie Curie was the first woman to win a Nobel Prize, awarded in 1903 for her work in physics.",
    "what is the longest bone in the human body": "The longest bone in the human body is the femur (thigh bone).",
    "how many hours are in a day": "There are 24 hours in a day.",
    "who was the first emperor of China": "The first emperor of China was Qin Shi Huang, who united China in 221 BC.",
    "what is the national flower of the United States": "The national flower of the United States is the rose.",
    "how many continents are there": "There are seven continents: Africa, Antarctica, Asia, Europe, North America, Australia, and South America.",
    "what is the currency of Australia": "The currency of Australia is the Australian Dollar (AUD).",
    "what is the most spoken language in the world": "The most spoken language in the world is English, followed closely by Mandarin Chinese.",
    "what is compost": "Compost is decayed organic material that is used as a natural fertilizer for plants.",
    "how often should I water my plants": "The frequency of watering depends on the plant and the weather. In general, water when the soil feels dry to the touch.",
    "what is the best time to plant tomatoes": "The best time to plant tomatoes is after the last frost date in your area, typically in spring.",
    "how do I prune a rose bush": "To prune a rose bush, cut back dead or damaged stems, and trim back the remaining healthy stems to encourage new growth.",
    "what is mulching": "Mulching is the process of covering the soil around plants with organic or inorganic materials to retain moisture, suppress weeds, and improve soil health.",
    "how do I get rid of weeds in my garden": "Weeds can be removed manually, with a hoe, or by using organic mulch to prevent their growth. Herbicides are also an option, but use them with caution.",
    "what is the difference between annual and perennial plants": "Annuals complete their life cycle in one year, while perennials live for more than two years and return every growing season.",
    "how do I grow basil": "Basil grows best in warm, sunny locations with well-drained soil. Water regularly, but avoid letting the plant sit in water.",
    "what is the best soil for growing vegetables": "Vegetables generally prefer loamy, well-drained soil with a pH level between 6.0 and 7.0.",
    "what are the best flowers for attracting pollinators": "Flowers like lavender, sunflowers, and bee balm are great for attracting bees, butterflies, and other pollinators.",
    "when should I prune my fruit trees": "Fruit trees should be pruned in late winter or early spring before new growth begins, while they are still dormant.",
    "how can I prevent pests in my garden": "Prevent pests by encouraging beneficial insects, using organic pesticides, rotating crops, and maintaining plant health.",
    "what is companion planting": "Companion planting is the practice of growing different types of plants together to benefit each other, such as planting basil near tomatoes to repel pests.",
    "how do I propagate succulents": "Succulents can be propagated by cutting off a healthy leaf or stem and allowing it to callous over before planting it in well-draining soil.",
    "what is the best fertilizer for indoor plants": "A balanced, water-soluble fertilizer is usually the best option for indoor plants. Look for one that contains equal amounts of nitrogen, phosphorus, and potassium.",
    "how do I grow carrots": "Carrots grow best in loose, well-drained soil. Sow the seeds directly in the ground and thin them out as they grow to allow space for the roots.",
    "why are my plant leaves turning yellow": "Yellowing leaves can indicate overwatering, underwatering, nutrient deficiencies, or disease. Check soil moisture and consider fertilizing.",
    "how do I know when to harvest my vegetables": "Harvest vegetables when they reach their mature size and color. For many vegetables, this is when they are firm and fully developed.",
    "what are the benefits of raised garden beds": "Raised garden beds improve drainage, reduce soil compaction, and make it easier to manage soil quality and plant care.",
    "how do I care for orchids": "Orchids need bright, indirect light, a humidity level of 50-70%, and to be watered once a week, letting the water drain away to avoid root rot.",
    "what is a greenhouse used for": "A greenhouse is used to create a controlled environment for plants, providing warmth, humidity, and protection from pests and weather conditions.",
    "how do I grow strawberries": "Strawberries thrive in full sun with well-drained soil. Space plants about 12-18 inches apart and water consistently.",
    "how can I improve my soil": "You can improve your soil by adding organic matter like compost, using cover crops, or adjusting the pH with lime or sulfur.",
    "how do I take care of a cactus": "Cacti need bright light and infrequent watering. Let the soil dry completely before watering again to avoid overwatering.",
    "what are some drought-tolerant plants": "Some drought-tolerant plants include lavender, succulents, yucca, and sage.",
    "how do I grow lettuce": "Lettuce grows best in cool weather, requiring rich, moist soil. Directly sow seeds in the ground and thin out the seedlings as they grow.",
    "how do I control aphids on my plants": "Aphids can be controlled with insecticidal soap, neem oil, or by encouraging natural predators like ladybugs.",
    "what is deadheading": "Deadheading is the practice of removing dead or spent flowers from plants to encourage further blooming and keep plants looking tidy.",
    "how can I improve the drainage in my garden": "To improve drainage, add organic material like compost to the soil, or create raised beds or mounds for better water flow.",
    "what are some good indoor plants": "Good indoor plants include spider plants, peace lilies, snake plants, and pothos, which thrive in low light and minimal care.",
    "how do I grow zucchini": "Zucchini grows best in rich, well-drained soil with plenty of sunlight. Plant the seeds directly in the ground and water regularly.",
    "how do I get rid of tomato blight": "Tomato blight can be managed by removing affected leaves and stems, using fungicides, and practicing crop rotation.",
    "when should I plant tulip bulbs": "Tulip bulbs should be planted in the fall, 6 to 8 weeks before the first frost, allowing them to establish roots before winter.",
    "what are hardy plants": "Hardy plants can survive cold temperatures and frost, often thriving in harsh weather conditions or winter climates.",
    "how do I grow potatoes": "Potatoes are grown from 'seed potatoes,' which are small tubers planted in well-drained, loose soil. They need plenty of sun and water.",
    "how can I prevent tomato blossom end rot": "Blossom end rot is caused by calcium deficiency. To prevent it, maintain consistent watering and ensure proper calcium levels in the soil.",
    "what is a worm bin": "A worm bin is a container where you can compost organic waste using worms, producing nutrient-rich worm castings that can be used as fertilizer.",
    "how do I deal with powdery mildew": "Powdery mildew can be controlled with fungicides or by removing affected leaves. Prevent it by ensuring proper air circulation around plants.",
    "what is companion planting for tomatoes": "Tomatoes grow well with basil, garlic, marigolds, and carrots. These companions help repel pests and enhance tomato growth.",
    "how do I take care of my hydrangea": "Hydrangeas need moist, well-drained soil and benefit from partial shade. Prune after blooming to maintain their shape.",
    "how do I start a vegetable garden": "Start a vegetable garden by choosing a sunny spot, preparing the soil with compost, and selecting the right vegetables for your climate.",
    "how can I prevent slugs in my garden": "To prevent slugs, try using diatomaceous earth, copper strips, or natural predators like ducks or birds.",
    "what are the benefits of using organic fertilizers": "Organic fertilizers improve soil structure, promote healthy root systems, and enhance long-term soil fertility without harming the environment.",
    "how do I prune my fruit trees": "Prune fruit trees in late winter or early spring, removing dead, diseased, or crossing branches and shaping the tree to improve air circulation.",
    "how do I grow beans": "Beans grow best in warm soil, and they need full sunlight. Plant them after the last frost, and water regularly to keep the soil moist.",
    "what is a pH level in soil": "The pH level in soil indicates its acidity or alkalinity. Most plants prefer a pH between 6.0 and 7.0.",
    "how do I attract butterflies to my garden": "To attract butterflies, plant nectar-rich flowers like milkweed, lavender, and coneflowers, and provide some open, sunny areas for basking.",
    "what is vermiculture": "Vermiculture is the practice of breeding and managing earthworms to help with composting organic waste and producing worm castings.",
    "how do I grow mint": "Mint grows best in moist, well-drained soil and full sun. Be careful, as it can spread aggressively in the garden.",
    "how do I know if my plants need more light": "If plants are stretching toward a light source, have pale or yellow leaves, or are growing slowly, they may need more light.",
    "what is a rain garden": "A rain garden is a planted area designed to capture and absorb rainwater runoff from impervious surfaces like roofs and driveways.",
    "how do I grow cucumbers": "Cucumbers need warm temperatures, full sunlight, and well-drained soil. Sow seeds directly in the soil after the last frost.",
    "what are the signs of overwatering plants": "Signs of overwatering include yellowing leaves, wilting, root rot, and a musty smell in the soil.",
    "how do I keep my garden free of pests naturally": "Encourage beneficial insects, use physical barriers, introduce companion plants, and apply natural insect repellents like neem oil or garlic spray.",
    "how do I propagate lavender": "To propagate lavender, take a cutting from a healthy stem and allow it to root in a pot with well-draining soil.",
    "what is soil erosion": "Soil erosion occurs when soil is washed away due to wind or water, often causing the loss of valuable topsoil in gardens and fields.",
    "what are some good plants for shade gardens": "Plants that thrive in shade include hostas, ferns, astilbes, and impatiens.",
    "how do I grow rhubarb": "Rhubarb thrives in cool climates with well-drained soil. Plant it in a sunny location and water regularly.",
    "what is the difference between organic and conventional gardening": "Organic gardening avoids synthetic chemicals and fertilizers, focusing on natural methods, while conventional gardening may use synthetic pesticides and fertilizers.",
    "how can I improve my garden soil naturally": "You can improve your soil by adding organic materials like compost, manure, and mulch, and by planting cover crops to enhance soil fertility.",
    "what are heirloom plants": "Heirloom plants are varieties that have been passed down through generations, typically grown from seeds saved from the previous season.",
    "how do I control aphids naturally": "Aphids can be controlled by spraying plants with a mixture of water and soap, attracting ladybugs, or using neem oil.",
    "how can I keep rabbits out of my garden": "To keep rabbits away, use fences, plant rabbit-repellent plants, or sprinkle blood meal or hot pepper flakes around the garden.",
    "how do I grow garlic": "Garlic is grown by planting cloves in the fall, about 2 inches deep in loose, well-drained soil. Harvest when the leaves turn yellow.",
    "what is the best way to store harvested vegetables": "Store vegetables in a cool, dark, and dry place. Some, like potatoes and carrots, do well in a root cellar, while others, like tomatoes, should be kept at room temperature.","worm bin": "A worm bin is a container where you can compost organic waste using worms.",
        "grow garlic": "Plant garlic cloves in fall in loose, well-drained soil. Harvest when the leaves turn yellow.",
        "water plants": "Most plants need watering when the top inch of soil is dry. Avoid overwatering.",
        "companion planting": "Companion planting is growing plants together to benefit each other, like tomatoes with basil.",
        "aphids control": "Use neem oil, introduce ladybugs, or spray soapy water to control aphids.",
        "best soil for vegetables": "Loamy soil with good drainage and organic matter is best for vegetables.",
        "start compost pile": "Layer green and brown organic materials and keep it moist for decomposition.",
        "pollinators": "Plant nectar-rich flowers like lavender, sunflowers, and wildflowers to attract pollinators.",
        "sunlight for tomatoes": "Tomatoes need at least 6-8 hours of direct sunlight per day.",
        "weed prevention": "Use mulch, landscape fabric, or hand-pull weeds regularly to prevent weeds.",
        "prune fruit tree": "Prune in late winter to remove dead branches and improve airflow.",
        "crop rotation": "Crop rotation prevents soil depletion by changing plant families in the same area yearly.",
        "heirloom seeds": "Heirloom seeds are open-pollinated, non-GMO seeds passed down for generations.",
        "mulching": "Mulching retains moisture, suppresses weeds, and improves soil health.",
        "water plants": "Water in the morning at the base of the plant to prevent fungal growth.",
        "organic fertilizer": "Use compost, banana peels, eggshells, and coffee grounds for nutrients.",
        "shade garden plants": "Hostas, ferns, astilbes, and bleeding hearts thrive in shade.",
        "protect plants from frost": "Use mulch, row covers, or bring potted plants indoors to prevent frost damage.",
        "grow potatoes": "Plant seed potatoes in loose soil, mound soil around stems as they grow.",
        "vermiculture": "Vermiculture is composting with worms to create nutrient-rich castings.",
        "grow herbs indoors": "Use pots with drainage, place them near a sunny window, and water moderately.",
        "blooming flowers": "Provide enough sunlight, deadhead spent blooms, and use phosphorus-rich fertilizer.",
        "nitrogen-fixing plants": "Legumes like beans and peas add nitrogen to the soil, improving fertility.",
        "test soil pH": "Use a soil test kit or vinegar and baking soda to check soil acidity or alkalinity.",
        "grow strawberries": "Plant strawberries in well-drained soil with full sunlight and mulch around them.",
        "drought-resistant plants": "Succulents, lavender, yarrow, and coneflowers thrive in dry conditions.",
        "propagate succulents": "Cut a leaf, let it dry for a few days, then plant it in soil.",
        "hydroponics": "Hydroponics is growing plants without soil, using nutrient-rich water solutions.",
        "keep slugs away": "Use crushed eggshells, diatomaceous earth, or beer traps to deter slugs.",
        "tomato blossom-end rot": "Ensure calcium-rich soil and consistent watering to prevent blossom-end rot.",
        "improve clay soil": "Add organic matter like compost, sand, or gypsum to loosen clay soil.",
        "container vegetables": "Tomatoes, peppers, lettuce, carrots, and herbs grow well in containers.",
        "compost tea": "Steep compost in water for 24-48 hours to create a nutrient-rich liquid fertilizer.",
        "grow blueberries": "Plant blueberries in acidic soil with full sunlight and mulch around them.",
        "deer control": "Use fencing, deer-resistant plants, or motion-activated sprinklers.",
        "grow cucumbers": "Plant cucumbers in warm soil with trellises for support and water regularly.",
        "butterfly garden": "Choose nectar-rich flowers like milkweed, verbena, and coneflowers.",
        "grow onions": "Plant onion sets in well-drained soil and harvest when the tops fall over.",
        "grow lavender": "Lavender prefers well-drained soil, full sun, and infrequent watering.",
        "cover crops": "Cover crops like clover and rye grass prevent erosion and improve soil fertility.",
        "prune roses": "Prune dead wood, shape the plant, and cut above outward-facing buds.",
        "grow carrots": "Carrots need loose, sandy soil and consistent moisture for even growth.",
        "grow lettuce": "Lettuce prefers cool temperatures, partial shade, and regular watering.",
        "grow peas": "Peas need cool weather and trellises for climbing, and they enrich the soil.",
        "greenhouse gardening": "Use a greenhouse to extend the growing season with controlled temperatures.",
        "store fresh herbs": "Hang herbs to dry, freeze them, or store in airtight containers.",
        "aeroponics": "Aeroponics is growing plants in an air or mist environment without soil.",
        "grow zucchini": "Plant zucchini in warm soil, space them well, and harvest young fruits."
    };

    function generateBotMessage(message) {
        const botMessage = document.createElement("div");
        botMessage.classList.add("message62", "bot-message");
        botMessage.textContent = message;
        chatContent.appendChild(botMessage);
        chatContent.scrollTop = chatContent.scrollHeight;
    }

    function generateUserMessage(message) {
        const userMessage = document.createElement("div");
        userMessage.classList.add("message62", "user-message");
        userMessage.textContent = message;
        chatContent.appendChild(userMessage);
        chatContent.scrollTop = chatContent.scrollHeight;
    }

    function getBotResponse(userMessage) {
        userMessage = userMessage.toLowerCase().replace(/[^\w\s]/g, ""); // Remove punctuation

        for (let key in knowledgeBase) {
            if (userMessage.includes(key)) {
                return knowledgeBase[key];
            }
        }

        return "Sorry, I don't understand that. Please ask something else.";
    }

    sendBtn.addEventListener("click", () => {
        const userMessage = userInput.value.trim();
        if (userMessage) {
            generateUserMessage(userMessage);
            const botResponse = getBotResponse(userMessage);
            setTimeout(() => generateBotMessage(botResponse), 500);
            userInput.value = "";
        }
    });

    userInput.addEventListener("keydown", (e) => {
        if (e.key === "Enter") {
            sendBtn.click();
        }
    });

    closeBtn.addEventListener("click", () => {
        document.getElementById("chatbot-container").style.display = "none";
    });
</script>



</div>

